# Default values for notifications.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global
global:
  # -- Kubernetes label `environment``
  environment: "development"

  # -- Google Cloud - Project ID (used for `Deployment` resource, `container.image` section)
  project_id: "example-12345"
  # -- Google Cloud - Region (used for `Deployment` resource, `container.image` section)
  region: "us-central1"

  # -- DNS domain (used for `HTTPRoute` resource)
  domain: "example.com"

  # Image
  image:
    # -- Repository ID
    repository: "accounts"
    # -- Tag; overrides the image tag whose default is the chart appVersion.
    tag: "latest"

# -- Replicas
replicas: 1

# -- Affinity (available region zones)
affinity:
  zones:
    - a

# Resources
resources:
  # -- Resources - Requests
  requests:
    cpu: "500m"
    memory: "1Gi"
  # -- Resources - Limits
  limits:
    cpu: "500m"
    memory: "1Gi"

# Autoscaling
autoscaling:
  # -- Vertical Pod Autoscaler
  vpa:
    # -- Vertical Pod Autoscaler - Maximum number of CPU & Memory, minimal number is `resources.requests` values
    max_allowed:
      cpu: "2000m"
      memory: "4Gi"

# ConfigMap (non - sensitive information)
configMap:
  # -- Network name
  network_name: ""
  # -- Chain ID
  chain_id: ""
  # -- Max blocks
  max_blocks: ""
  # -- Timeout interval (ms)
  timeout_interval: ""

# Secret (sensitive information, defined through environment variables)
secret:
  # -- MongoDB Atlas URI (mongodb://username:password@hostname:port/database?params)
  mongo_uri: ""
  # -- smart-wallets - JWT secret
  smart_wallets_jwt_secret: ""
  # -- RPC URL - Standard - Fuse
  rpc_url: ""
  # -- RPC URL - Archive - Fuse
  full_archive_rpc_url: ""
