export const operatorJwtString = 'operator_jwt_strategy'
export const operatorWalletModelString = 'OPERATOR_WALLET_MODEL'
export const operatorRefreshTokenModelString = 'OPERATOR_REFRESH_TOKEN_MODEL'
export const operatorInvoiceModelString = 'OPERATOR_INVOICE_MODEL'
export const operatorCheckoutModelString = 'OPERATOR_CHECKOUT_MODEL'
