# Default values for centrifugo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global
global:
  # Namespace & Environment
  namespace: ""
  environment: ""

  # DNS domain
  domain: ""

# Image
image:
  repository: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Resources (requests & limits)
resources:
  requests:
    cpu: ""
    memory: ""
  limits:
    cpu: ""
    memory: ""

# Secrets
#
# Note: Component use config.json file which's taking from Secret Manager via Helm {{ .Files.Get }} function
# secrets:
#   ...
#   ...
