# Default values for centrifugo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global
global:
  # -- Label 'environment'
  environment: ""

  # -- DNS domain
  domain: ""

# Image
image:
  # -- Repository ID
  repository: ""
  # -- Tag; overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Replicas
replicas: 1

# -- Affinity (available region zones)
affinity:
  zones:

# Resources
resources:
  # -- Resources - Requests
  requests:
    cpu: ""
    memory: ""
  # -- Resources - Limits
  limits:
    cpu: ""
    memory: ""

# Autoscaling
autoscaling:
  # -- Autoscaling - Maximum replicas value. Note: minimum replicas value equals `replicas` value (Horizontal Pod Autoscaler)
  max_replicas: 5
  # -- Autoscaling - CPU threshold (in percent, Horizontal Pod Autoscaler)
  cpu:
    threshold: 80
  # -- Autoscaling - RAM threshold (in percent, Horizontal Pod Autoscaler)
  memory:
    threshold: 80
  # -- Autoscaling - RPS threshold (in percent, Horizontal Pod Autoscaler)
  rps:
    threshold: 80

# Service
service:
  # -- Service - Annotations
  annotations:
    # -- Service - Annotations - RPS per pod
    networking.gke.io/max-rate-per-endpoint: 10

# -- Logging - enabled (`true` or `false`), sampleRate (from 0 to 500000 / 1000000)
logging:
  enabled: false

# Secrets
#
# Note: Component use config.json file which's taking from Secret Manager via Helm {{ .Files.Get }} function.
