# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global
global:
  # -- Kubernetes label `environment``
  environment: "development"

  # -- Google Cloud - Project ID (used for `Deployment` resource, `container.image` section)
  project_id: "example-12345"
  # -- Google Cloud - Region (used for `Deployment` resource, `container.image` section)
  region: "us-central1"

  # -- DNS domain (used for `HTTPRoute` resource)
  domain: "example.com"

  # Image
  image:
    # -- Repository ID
    repository: "api"
    # -- Tag; overrides the image tag whose default is the chart appVersion.
    tag: "latest"

# -- Replicas
replicas: 1

# -- Affinity (available region zones)
affinity:
  zones:
    - a

# Resources
resources:
  # -- Resources - Requests
  requests:
    cpu: "500m"
    memory: "1Gi"
  # -- Resources - Limits
  limits:
    cpu: "500m"
    memory: "1Gi"

# Autoscaling
autoscaling:
  # -- Horizontal Pod Autoscaler
  hpa:
    # -- Horizontal Pod Autoscaler - Maximum number of replicas, minimal number is `replicas` value
    max_replicas: 5

# Service
service:
  # -- Service - Annotations
  annotations:
    # -- Service - Annotations - RPS per pod
    networking.gke.io/max-rate-per-endpoint: 10

# -- Logging - enabled (`true` or `false`), sampleRate (from 0 to 500000 / 1000000)
logging:
  enabled: true
  sampleRate: 1000000

# ConfigMap (non - sensitive information)
configMap:
  # -- Charge - Wallet phone number
  charge_wallet_phone_number: ""
  # -- Charge - Base URL
  charge_base_url: ""
  # -- Job sleep (ms)
  job_sleep_ms: ""
  # -- Unmarshal - Base URL
  unmarshal_base_url: ""
  # -- Alchemy - Base URL
  alchemy_base_url: ""
  # -- Ethereum - Payments network name
  ethereum_payments_network_name: ""

# Secret (sensitive information, defined through environment variables)
secret:
  # -- MongoDB Atlas URI (mongodb://username:password@hostname:port/database?params)
  mongo_uri: ""
  # -- Charge - Public key
  charge_public_key: ""
  # -- Charge - Secret key
  charge_secret_key: ""
  # -- Charge - Webhook ID
  charge_webhook_id: ""
  # -- Unmarshal - Auth key
  unmarshal_auth_key: ""
  # -- Charge - Payments Ethereum mnemonic
  charge_payments_ethereum_mnemonic: ""
  # -- Alchemy - Webhook ID
  alchemy_webhook_id: ""
  # -- Alchemy - Auth key
  alchemy_auth_key: ""
