apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
  namespace: {{ .Release.Namespace }}
  labels:
    app: apps
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: apps
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: apps
        environment: {{ .Values.global.environment }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                {{- range $zone := .Values.affinity.zones }}
                  - {{ $.Values.global.region }}-{{ $zone }}
                {{- end }}
      containers:
        - name: apps
          image: "{{ .Values.global.region }}-docker.pkg.dev/{{ .Values.global.project_id }}/{{ .Values.global.image.repository }}/apps:{{ .Values.global.image.tag }}"
          imagePullPolicy: Always
          env:

            # ConfigMap
            - name: APPS_HOST
              valueFrom:
                configMapKeyRef:
                  name: apps
                  key: apps_host
            - name: APPS_PORT
              valueFrom:
                configMapKeyRef:
                  name: apps
                  key: apps_port
            - name: APPS_TCP_PORT
              valueFrom:
                configMapKeyRef:
                  name: apps
                  key: apps_tcp_port
            {{- range $key, $value := .Values.configMap }}
            - name: {{ $key | upper }}
              valueFrom:
                configMapKeyRef:
                  name: apps
                  key: {{ $key }}
            {{- end }}

            # Secret
            {{- range $key, $val := .Values.secret }}
            - name: {{ $key | upper }}
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: {{ $key }}
            {{- end }}

          # Ports
          ports:
            - containerPort: 5006
              name: http
            - containerPort: 8880
              name: tcp
          
          # Probes
          livenessProbe:
            httpGet:
              path: /app-store/v1/health
              port: 5006
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /app-store/v1/health
              port: 5006
            initialDelaySeconds: 5
            periodSeconds: 5
          
          # Resources
          resources:
            requests:
            {{- range $key, $val := .Values.resources.requests }}
              {{ $key }}: {{ $val | quote }}
            {{- end }}
            limits:
            {{- range $key, $val := .Values.resources.limits }}
              {{ $key }}: {{ $val | quote }}
            {{- end }}
