apiVersion: v1
kind: Service
metadata:
  name: apps
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.gke.io/max-rate-per-endpoint: {{ .Values.maxRatePerEndpoint | quote }}
  labels:
    app: apps
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: apps
    environment: {{ .Values.global.environment }}
  ports:
    - name: http
      protocol: TCP
      port: 5006
      targetPort: 5006
    - name: tcp
      protocol: TCP
      port: 8880
      targetPort: 8880
  type: ClusterIP
