export const apiService = 'CHARGE_API_SERVICE'
export const notificationsService = 'CHARGE_NOTIFICATIONS_SERVICE'
export const relayService = 'CHARGE_RELAY_SERVICE'
export const accountsServiceLoggerContext = 'ACCOUNTS-SERVICE'
export const apiServiceLoggerContext = 'API-SERVICE'
export const notificationsServiceLoggerContext = 'NOTIFICATIONS-SERVICE'
export const networkServiceContext = 'NETWORK-SERVICE'
