export const apiService = 'CHARGE_API_SERVICE'
export const relayService = 'CHARGE_RELAY_SERVICE'
export const accountsServiceHost = 'charge-accounts-service'
export const apiServiceHost = 'charge-api-service'
export const relayServiceHost = 'charge-relay-service'
