openapi: 3.0.0
info:
  title: Payments API
  version: 1.0.0
servers:
  - url: https://api.chargeweb3.com/api/v0
paths:
  /app-store/v1/payments/payment_link:
    post:
      tags:
        - payments
      summary: Create Payment Link
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Title
                description: Description
                amount: '10'
                tokenAddress: '0x495d133B938596C9984d462F007B676bDc57eCEC'
                tokenSymbol: G$
      parameters:
        - name: API-SECRET
          in: header
          schema:
            type: string
          example: '{{paymentsSecretKey}}'
        - name: apiKey
          in: query
          schema:
            type: string
          example: '{{paymentsPublicKey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /app-store/v1/payments/payment_links:
    get:
      tags:
        - payments
      summary: Get Payment Links
      parameters:
        - name: API-SECRET
          in: header
          schema:
            type: string
          example: '{{paymentsSecretKey}}'
        - name: apiKey
          in: query
          schema:
            type: string
          example: '{{paymentsPublicKey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /app-store/v1/payments/payment_link/{paymentLinkId}:
    get:
      tags:
        - payments
      summary: Get Payment Link
      parameters:
        - name: paymentLinkId
          in: path
          schema:
            type: string
          required: true
          example: 635539a59b40a1154fb2d0c0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /app-store/v1/payments/account_balance:
    get:
      tags:
        - payments
      summary: Get Account Balance
      parameters:
        - name: API-SECRET
          in: header
          schema:
            type: string
          example: '{{paymentsSecretKey}}'
        - name: apiKey
          in: query
          schema:
            type: string
          example: '{{paymentsPublicKey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
