apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    environment: {{ .Values.global.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.max_replicas }}
  metrics:

    # CPU
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    
    # Memory
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

    # Requests / second
    - type: Object
      object:
        describedObject:
          kind: Service
          name: accounts
        metric:
          name: "autoscaling.googleapis.com|gclb-capacity-utilization"
        target:
          averageValue: 80
          type: AverageValue
