apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: relay
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay
    environment: {{ .Values.global.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: relay
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.max_replicas }}
  metrics:

    # CPU
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    
    # Memory
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
