apiVersion: v1
kind: Secret
metadata:
  name: relay
  namespace: {{ .Values.global.namespace }}
stringData:
  mongo_uri: {{ .Values.secrets.mongo_uri }}
  relay_secret: {{ .Values.secrets.relay_secret }}
