apiVersion: v1
kind: Secret
metadata:
  name: relay
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  relay_secret: {{ .Values.secrets.relay_secret | b64enc }}
