apiVersion: v1
kind: ConfigMap
metadata:
  name: amplitude
  namespace: {{ .Release.Namespace }}
  labels:
    app: amplitude
    environment: {{ .Values.global.environment }}
data:
  nginx.conf: |
    worker_processes auto;
    worker_rlimit_nofile 10000;
    worker_shutdown_timeout 65s;

    events {
      worker_connections 1024;
      accept_mutex off;
      use epoll;
      multi_accept on;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;

      # Real IP
      set_real_ip_from 127.0.0.1;
      set_real_ip_from 10.0.0.0/8;
      set_real_ip_from 172.16.0.0/12;
      set_real_ip_from 192.168.0.0/16;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;

      # Logs
      map "$time_local:$msec" $time_local_ms {
        ~(^\S+)(\s+\S+):\d+\.(\d+)$ $1.$3$2;
      }

      log_format main escape=json
      '$remote_addr - $realip_remote_addr - $request_time - [$time_local_ms] - $msec - '
      '$http_x_amzn_trace_id - $request_id - $connection-$connection_requests - '
      '$scheme - $host - $server_port - $ssl_protocol - $ssl_cipher - '
      '$request_method - $request_uri - $server_protocol - $status - $request_completion - '
      '$bytes_sent - $request_length - "$http_referer" - "$http_user_agent" - '
      '$proxy_host - "$upstream_addr" - "$upstream_status" - "$upstream_connect_time" - "$upstream_response_time" ';

      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/error.log info;

      # Compression
      gzip on;
      gzip_min_length 1000;
      gzip_comp_level 3;
      gzip_types text/plain text/css application/json application/javascript application/x-javascript text/javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml;

      # Timeouts
      keepalive_timeout 65s;
      client_header_timeout 10s;
      client_body_timeout 30s;
      send_timeout 65s;

      # Request
      client_max_body_size 100M;

      # Response
      charset utf-8;

      # Proxy
      proxy_connect_timeout 65s;
      proxy_send_timeout 65s;
      proxy_read_timeout 65s;

      proxy_buffering off;
      proxy_buffers 8 64k;
      proxy_buffer_size 64k;
      proxy_busy_buffers_size 128k;

      proxy_http_version 1.1;
      proxy_intercept_errors off;

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $server_name;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header Connection "";
      add_header Front-End-Https on;
      proxy_redirect off;

      # Server
      server {
        listen 8888 deferred default_server;

        location /amplitude {
          proxy_pass https://api2.amplitude.com/2/httpapi;
        }

        location /health {
          # Because default content-type is application/octet-stream,
          # browser will offer to "save the file"...
          # if you want to see reply in browser, uncomment next line 
          add_header Content-Type text/plain;
          
          # Location was created for cloud health check
          return 200 '{"health": "ok"}';
        }
      }
    }
