apiVersion: v1
kind: ConfigMap
metadata:
  name: amplitude
  namespace: {{ .Release.Namespace }}
  labels:
    app: amplitude
    environment: {{ .Values.global.environment }}
data:
  nginx.conf: |
    worker_processes auto;

    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      sendfile on;

      # Logs
      map "$time_local:$msec" $time_local_ms {
        ~(^\S+)(\s+\S+):\d+\.(\d+)$ $1.$3$2;
      }

      log_format main escape=json
      '$remote_addr - $realip_remote_addr - $request_time - [$time_local_ms] - $msec - '
      '$http_x_amzn_trace_id - $request_id - $connection-$connection_requests - '
      '$scheme - $host - $server_port - $ssl_protocol - $ssl_cipher - '
      '$request_method - $request_uri - $server_protocol - $status - $request_completion - '
      '$bytes_sent - $request_length - "$http_referer" - "$http_user_agent" - '
      '$proxy_host - "$upstream_addr" - "$upstream_status" - "$upstream_connect_time" - "$upstream_response_time" ';

      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/error.log info;

      # Timeouts
      keepalive_timeout 65s;

      # Server
      server {
        listen 8888 deferred default_server;

        location /amplitude {
          proxy_pass https://api2.amplitude.com/2/httpapi;
        }

        location /health {
          # Because default content-type is application/octet-stream,
          # browser will offer to "save the file"...
          # if you want to see reply in browser, uncomment next line 
          add_header Content-Type text/plain;
          
          # Location was created for cloud health check
          return 200 '{"health": "ok"}';
        }
      }
    }
