kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: amplitude
  namespace: {{ .Release.Namespace }}
  labels:
    app: amplitude
    environment: {{ .Values.global.environment }}
spec:
  parentRefs:
    - kind: Gateway
      name: "{{ .Release.Namespace }}-lb"
      sectionName: https
  hostnames:
    - "analytics.{{ .Values.global.domain }}"
  rules:
    - matches:
        - path:
            value: /health
            type: Exact
        - path:
            value: /amplitude
            type: Exact
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: application
                value: amplitude
      backendRefs:
        - name: amplitude
          port: 8888
