apiVersion: v1
kind: Service
metadata:
  name: amplitude
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.gke.io/max-rate-per-endpoint: {{ .Values.maxRatePerEndpoint | quote }}
  labels:
    app: amplitude
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: amplitude
    environment: {{ .Values.global.environment }}
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
