apiVersion: v1
kind: Secret
metadata:
  name: notifications
  namespace: {{ .Release.Namespace }}
  labels:
    app: notifications
    environment: {{ .Values.global.environment }}
type: Opaque
data:

  # User - defined
{{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
