# Default values for fusebox-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# - Global
global:
  # Label: environment
  environment: "staging"

  # Google Cloud
  project_id: "fusebox-staging"
  region: "europe-west1"

  # ClusterSecretStore name (should be created before apply)
  clusterSecretStore: "google-cloud-secret-manager-store"

  # DNS domain
  domain: "staging.fuse.io"

  # Image
  image:
    repository: "fusebox-staging"
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

# - Components
accounts:
  enabled: true

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "250m"
      memory: "500Mi"

  # Service - RPS per Pod
  maxRatePerEndpoint: 50

  # Security - CloudArmor
  securityPolicy: "fusebox-staging-accounts-security-policy"

  # ConfigMap
  configMap:
    auth0_issuer_url: "https://auth.staging.fuse.io/"
    auth0_audience: "https://accounts.staging.fuse.io"
    paymaster_sandbox_contract_address_v_0_1_0: "0x324999f067EA822EEf78e7A4793F672A4F5E80f6"
    paymaster_production_contract_address_v_0_1_0: "0xEA1Ba4305A07cEd2bB5e42224D71aBE0BC3C3f28"
    entrypoint_sandbox_contract_address_v_0_1_0: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
    entrypoint_production_contract_address_v_0_1_0: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
    etherspot_wallet_factory_sandbox_contract_address_v_0_1_0: "0x7f6d8F107fE8551160BD5351d5F1514A6aD5d40E"
    etherspot_wallet_factory_production_contract_address_v_0_1_0: "0x7f6d8F107fE8551160BD5351d5F1514A6aD5d40E"
    paymaster_funder_api_key: "pk_u_RbFw7NQBB7ZQIFJtziLE_S"
    paymaster_funder_webhook_id: "65bbbc63fc2f925de8e1a561"

  # Secret (external; sensitive information; pulled from Google Cloud, Secret Manager)
  secret:
    - mongo_uri
    - smart_wallets_jwt_secret
    - paymaster_funder_private_key
    - paymaster_funder_api_secret_key
    - amplitude_api_key
    - incoming_token_transfers_webhook_id
    - google_operator_form_url

amplitude:
  enabled: false # We use reverse Amplitude proxy only for Production.

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # Service - RPS per Pod
  maxRatePerEndpoint: 10

api:
  enabled: true

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "250m"
      memory: "500Mi"

  # Service - RPS per Pod
  maxRatePerEndpoint: 50

  # Security - CloudArmor
  securityPolicy: "fusebox-staging-api-security-policy"

  # ConfigMap
  configMap:
    explorer_api_url: "https://explorer.fuse.io/api"
    qa_mode: "true"
    bundler_api_prd_url: "https://fuse-bundler.etherspot.io"
    bundler_api_sandbox_url: "https://testnet-rpc.etherspot.io/v1/123"
    spark_rpc_url: "https://rpc.fusespark.io"
    legacy_fuse_admin_api_url: "https://studio.fuse.io"
    legacy_fuse_wallet_api_url: "https://staging-wallet.fuse.io"
    legacy_fuse_trade_api_url: "https://api.fuseswap.com"
    voltage_router_api_url: "https://router.voltage.finance"

  # Secret (external; sensitive information; pulled from Google Cloud, Secret Manager)
  secret:
    - mongo_uri
    - rpc_url
    - fuse_studio_admin_jwt
    - legacy_jwt_secret
    - smart_wallets_jwt_secret
    - paymaster_production_signer_private_key_v_0_1_0
    - paymaster_sandbox_signer_private_key_v_0_1_0
    - explorer_api_key

apps:
  enabled: false # [DEPRECATED]

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # Service - RPS per Pod
  maxRatePerEndpoint: 10

  # Security - CloudArmor
  securityPolicy: null

  # ConfigMap
  configMap:
    charge_wallet_phone_number: "+15554443322"
    charge_base_url: "https://api.staging.fuse.io"
    job_sleep_ms: "6000"
    unmarshal_base_url: "https://api.unmarshal.com"
    alchemy_base_url: "https://dashboard.alchemy.com/api/update-webhook-addresses"
    ethereum_payments_network_name: "goerli"

  # Secret (external; sensitive information; pulled from Google Cloud, Secret Manager)
  secret:
    - mongo_uri
    - charge_public_key
    - charge_secret_key
    - charge_payment_links_webhook_id
    # - charge_webhook_id
    # - unmarshal_auth_key
    # - charge_payments_ethereum_mnemonic
    # - alchemy_webhook_id
    # - alchemy_auth_key

centrifugo:
  enabled: true

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Image
  image:
    repository: "centrifugo/centrifugo"
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v5.2.2"

  # Service - RPS per Pod
  maxRatePerEndpoint: 50

  # Security - CloudArmor
  securityPolicy: null

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "250m"
      memory: "500Mi"

gateway-api:
  enabled: true

  name: "fusebox-staging-lb"
  global_address: "fusebox-staging-lb"

network:
  enabled: true

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    legacy_fuse_trade_api_url: "https://api.fuseswap.com"
    primary_service: "unmarshal"
    explorer_api_url: "https://explorer.fuse.io/api"
    unmarshal_base_url: "https://api.unmarshal.com"

  # Secret (external; sensitive information; pulled from Google Cloud, Secret Manager)
  secret:
    - rpc_url
    - unmarshal_auth_key
    - explorer_api_key

notifications:
  enabled: true

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  # ConfigMap
  configMap:
    network_name: "fuse"
    chain_id: "122"
    max_blocks: "2500"
    timeout_interval: "10000"

  # Secret (external; sensitive information; pulled from Google Cloud, Secret Manager)
  secret:
    - mongo_uri
    - smart_wallets_jwt_secret
    - rpc_url
    - full_archive_rpc_url

relay:
  enabled: false # [DEPRECATED]

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # Secret (external; sensitive information; pulled from Google Cloud, Secret Manager)
  secret:
    - mongo_uri
    - relay_secret

skandha:
  enabled: false # Only Production environment has self - hosted Skandha instance for a DR; Ethrespot - hosted endpoint used by both environments.

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Image
  image:
    repository: "etherspot/skandha"
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.41-alpha"

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # Service - RPS per Pod
  maxRatePerEndpoint: 10

  # Security - CloudArmor
  securityPolicy: null

smart-wallets:
  enabled: true

  # Replicas
  replicas: 1

  # Affinity (zones)
  affinity:
    zones:
      - b

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    centrifugo_uri: "wss://ws.staging.fuse.io/connection/websocket"
    centrifugo_api_url: "https://ws.staging.fuse.io/api"
    legacy_fuse_wallet_api_url: "https://staging-wallet.fuse.io"
    charge_base_url: "https://api.staging.fuse.io"
    legacy_fuse_trade_api_url: "https://api.fuseswap.com"

  # Secret (external; sensitive information; pulled from Google Cloud, Secret Manager)
  secret:
    - amplitude_api_key
    - mongo_uri
    - smart_wallets_jwt_secret
    - fuse_wallet_backend_jwt
    - centrifugo_jwt
    - centrifugo_api_key
    - charge_public_key
    - charge_secret_key
    - incoming_token_transfers_webhook_id