# Default values for charge-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# - Global -
global:
  # Label: environment
  environment: "staging"

  # Google Cloud
  project_id: "fusebox-staging"
  region: "europe-west1"

  # DNS domain
  domain: "staging.fuse.io"

  # Image
  image:
    repository: "fusebox-staging"
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

# - Load balancing -
gateway-api:
  name: "fusebox-staging-lb"
  global_address: "fusebox-staging-lb"

# - Components -
accounts:
  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    auth0_issuer_url: "https://auth.staging.fuse.io/"
    auth0_audience: "https://accounts.staging.fuse.io"
    paymaster_sandbox_contract_address_v_0_1_0: "0x324999f067EA822EEf78e7A4793F672A4F5E80f6"
    paymaster_production_contract_address_v_0_1_0: "0xEA1Ba4305A07cEd2bB5e42224D71aBE0BC3C3f28"
    entrypoint_sandbox_contract_address_v_0_1_0: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
    entrypoint_production_contract_address_v_0_1_0: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"

  # Secrets (through CI/CD process via environment variables)
  secrets:
    mongo_uri: ""

api:
  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    explorer_api_url: "https://explorer.fuse.io/api"
    qa_mode: "true"
    bundler_api_prd_url: "https://bundler.fuse.io/122"
    bundler_api_sandbox_url: "https://bundler.fuse.io/123"
    spark_rpc_url: "https://rpc.fusespark.io/"
    legacy_fuse_admin_api_url: "https://studio.fuse.io"
    legacy_fuse_wallet_api_url: "https://wallet.fuse.io"
    legacy_fuse_trade_api_url: "https://api.fuseswap.com"

  # Secrets (through CI/CD process via environment variables)
  secrets:
    mongo_uri: ""
    rpc_url: ""
    fuse_studio_admin_jwt: ""
    legacy_jwt_secret: ""
    smart_wallets_jwt_secret: ""
    paymaster_production_signer_private_key_v_0_1_0: ""
    paymaster_sandbox_signer_private_key_v_0_1_0: ""

relay:
  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # Secrets (through CI/CD process via environment variables)
  secrets:
    mongo_uri: ""
    relay_secret: ""

notifications:
  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    network_name: "fuse"
    chain_id: "122"
    max_blocks: "2500"
    timeout_interval: "10000"

  # Secrets (through CI/CD process via environment variables)
  secrets:
    mongo_uri: ""
    smart_wallets_jwt_secret: ""
    rpc_url: ""
    full_archive_rpc_url: ""

network:
  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    legacy_fuse_trade_api_url: "https://api.fuseswap.com"

apps:
  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    charge_wallet_phone_number: "+15554443322"
    charge_base_url: "https://api.staging.fuse.io"
    job_sleep_ms: "6000"
    unmarshal_base_url: "https://api.unmarshal.com"
    alchemy_base_url: "https://dashboard.alchemy.com/api/update-webhook-addresses"
    ethereum_payments_network_name: "goerli"

  # Secrets (through CI/CD process via environment variables)
  secrets:
    mongo_uri: ""
    charge_public_key: ""
    charge_secret_key: ""
    charge_webhook_id: ""
    unmarshal_auth_key: ""
    charge_payments_ethereum_mnemonic: ""
    alchemy_webhook_id: ""
    alchemy_auth_key: ""

smart-wallets:
  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # ConfigMap
  configMap:
    centrifugo_uri: "wss://ws.staging.fuse.io/connection/websocket"
    centrifugo_api_url: "https://ws.staging.fuse.io/api"
    legacy_fuse_wallet_api_url: "https://staging-wallet.fuse.io"

  # Secrets (through CI/CD process via environment variables)
  secrets:
    mongo_uri: ""
    smart_wallets_jwt_secret: ""
    fuse_wallet_backend_jwt: ""
    centrifugo_jwt: ""
    centrifugo_api_key: ""

centrifugo:
  # Image
  image:
    repository: "centrifugo/centrifugo"
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v5"

  # Resources (requests & limits)
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Secrets (through CI/CD process via environment variables)
#
# Note: Component use config.json file which's taking from Secret Manager via Helm {{ .Files.Get }} function
# secrets:
#   ...
#   ...
