apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: centrifugo
  namespace: {{ .Release.Namespace }}
  labels:
    app: centrifugo
    environment: {{ .Values.global.environment }}
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 5
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000
        portName: http
        host: centrifugo
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: centrifugo
