kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: centrifugo
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - kind: Gateway
      name: "{{ .Values.global.namespace }}-lb"
      sectionName: https
  hostnames:
    - "ws.{{ .Values.global.domain }}"
  rules:
    - matches:
        - path:
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: application
                value: centrifugo
      backendRefs:
        - name: centrifugo
          port: 8000
