kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: centrifugo
  namespace: {{ .Release.Namespace }}
  labels:
    app: centrifugo
    environment: {{ .Values.global.environment }}
spec:
  parentRefs:
    - kind: Gateway
      name: "{{ .Release.Namespace }}-lb"
      sectionName: https
  hostnames:
    - "ws.{{ .Values.global.domain }}"
  rules:
    - matches:
        - path:
            type: Exact
            value: /
        - path:
            type: Exact
            value: /favicon.png
        - path:
            type: PathPrefix
            value: /admin
        - path:
            type: PathPrefix
            value: /static
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /connection
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: application
                value: centrifugo
      backendRefs:
        - name: centrifugo
          port: 8000
