apiVersion: v1
kind: Secret
metadata:
  name: centrifugo
  namespace: {{ .Release.Namespace }}
  labels:
    app: centrifugo
    environment: {{ .Values.global.environment }}
type: Opaque
data:
    config.json: |-
        {{ .Files.Get "config.json" | b64enc }}
