apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: accounts
  namespace: {{ .Release.Namespace }}
  labels:
    app: accounts
    environment: {{ .Values.global.environment }}
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 5
    config:
      type: HTTP
      httpHealthCheck:
        port: 5001
        portName: http
        host: accounts
        requestPath: /accounts/v1/health
  targetRef:
    group: ""
    kind: Service
    name: accounts
