apiVersion: v1
kind: Secret
metadata:
  name: accounts
  namespace: {{ .Release.Namespace }}
  labels:
    app: accounts
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  
  # User - defined
{{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
