apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.gke.io/max-rate-per-endpoint: {{ .Values.maxRatePerEndpoint | quote }}
  labels:
    app: accounts
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: accounts
    environment: {{ .Values.global.environment }}
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: tcp
      protocol: TCP
      port: 8875
      targetPort: 8875
  type: ClusterIP
