apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: network
  namespace: {{ .Release.Namespace }}
  labels:
    app: network
    environment: {{ .Values.global.environment }}
spec:
  refreshInterval: 5m # Pull rate Secret Manager secrets from Google Cloud
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.global.clusterSecretStore }}
  target:
    name: network
    creationPolicy: Owner
  data:
{{- range .Values.secret }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Release.Namespace }}-network-{{ . }}
{{- end }}


