apiVersion: v1
kind: Service
metadata:
  name: network
  namespace: {{ .Release.Namespace }}
  labels:
    app: network
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: network
    environment: {{ .Values.global.environment }}
  ports:
    - name: http
      protocol: TCP
      port: 5005
      targetPort: 5005
    - name: tcp
      protocol: TCP
      port: 8879
      targetPort: 8879
  type: ClusterIP
