apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-wallets
  namespace: {{ .Release.Namespace }}
  labels:
    app: smart-wallets
    environment: {{ .Values.global.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-wallets
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.autoscaling.max_replicas }}
  metrics:

    # CPU
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.cpu.threshold }}
    
    # Memory
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.memory.threshold }}
